workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    working_directory: mobile
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      
    triggering:
      events:
        - push
        - pull_request
      branch:
        include:
          - main
          - develop

    scripts:
      - name: Get Flutter packages
        script: flutter pub get
          
      - name: Analyze
        script: flutter analyze
          
      - name: Build debug APK
        script: flutter build apk --debug
          
      - name: Build release APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - avicenna@health.dev
        notify:
          success: true
          failure: true
